### ISSUE TITLE
Definition of underlay path and additional steering constraints to be considered.

### ISSUE THREAD

**Issue by aguoietf** [lana-wu/ietf-ns-nbi#76]
In the ietf-ns-topology data model we currently have the following augments based on ietf-ns-nbi which are generic and may be considered by this model:

1. a steering constraint for disjointness between different connections of a connection group. Possible values of the disjointness include link, node and SRLG disjointness. For example,

~~~
  augment /ietf-nss:network-slice-services/ietf-nss:slice-service
            /ietf-nss:connection-groups/ietf-nss:connection-group
            /ietf-nss:slo-sle-policy/ietf-nss:custom
            /ietf-nss:service-slo-sle-policy/ietf-nss:sle-policy
            /ietf-nss:steering-constraints:
    +--rw disjointness?   te-types:te-path-disjointness
~~~

2. Underlay path definition associated with an RFC8345 topology. For example,
~~~
  augment /ietf-nss:network-slice-services/ietf-nss:slice-service
            /ietf-nss:connection-groups/ietf-nss:connection-group
            /ietf-nss:slo-sle-policy/ietf-nss:custom
            /ietf-nss:service-slo-sle-policy/ietf-nss:sle-policy
            /ietf-nss:steering-constraints/ietf-nss:path-constraints:
    +--rw network-ref?    -> /nw:networks/network/network-id
    +--rw path-element* [index]
       +--rw index            uint32
       +--rw is-strict-hop?   boolean
       +--rw (type)?
          +--:(node-hop)
          |  +--rw node-id?   nw:node-id
          +--:(link-hop)
          |  +--rw link-id?   nt:link-id
          +--:(tp-hop)
             +--rw tp-id?     nt:tp-id
~~~

**Comment by lana-wu** [comment]
Is the second extension related to "custom-topology" or a new network? The text mentions the **underlay path of the network**. As per NS framework, the underlay network is not supposed to exposed to customers.
Please refer the text from NS framework:
_Security: The underlay network components are less exposed to attack because the underlay network (or network operator) does not need to expose network details (topology, capacity, etc.) to the IETF Network Slice Service customers_
